// Generated by CoffeeScript 1.4.0
var brix;

module.exports = brix = {
  configure: function(stacker, config) {
    brix.server = new (require('./server'))(config);
    return brix.server.start();
  },
  edge: function(placeholder, nodes) {}
};
